import { ErrorMode } from '..';
import { pMap } from './pMap';
/**
 * Like pMap, but doesn't fail on errors, instead returns both successful results and errors.
 */
export async function pBatch(iterable, mapper, opt) {
    try {
        const results = await pMap(iterable, mapper, Object.assign(Object.assign({}, opt), { errorMode: ErrorMode.THROW_AGGREGATED }));
        return {
            results,
            errors: [],
        };
    }
    catch (err) {
        const { errors, results } = err;
        if (!errors || !results)
            throw err; // not an AggregatedError
        return {
            results,
            errors,
        };
    }
}
